spring:
  application:
    name: rabbithole
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-grc8v6ad25njr8sw.us.auth0.com/
          jwk-set-uri: https://dev-grc8v6ad25njr8sw.us.auth0.com/.well-known/jwks.json

auth0:
  audience: https://dev-grc8v6ad25njr8sw.us.auth0.com/api/v2/
  issuer: https://dev-grc8v6ad25njr8sw.us.auth0.com/