spring:
  application:
    name: rabbithole
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-grc8v6ad25njr8sw.us.auth0.com/
          jwk-set-uri: https://dev-grc8v6ad25njr8sw.us.auth0.com/.well-known/jwks.json